/* ============================================================
   Process Atlas · Teams Squared
   Data model: departments → workflows → spine steps + variants
   Spine steps are drawn from the observed AW+screenshot
   transcripts (candidate_workflows_screenshots.md).
   Variant traversal counts are synthetic for the demo.
   Each step carries a one-line `summary` of what was observed.
   ============================================================ */

const PEOPLE = [
  { id: 'piyara',  name: 'Piyara Wijekoon',      role: 'HR Mgmt / ISO Compliance' },
  { id: 'himaya',  name: 'Himaya Gunawardena',    role: 'HR Operations Specialist' },
  { id: 'jerome',  name: 'Jerome Verallo',        role: 'Marketing Ops / Rec. Data' },
  { id: 'zolara',  name: 'Zolara Peiris',         role: 'Talent Acquisition' },
  { id: 'samindi', name: 'Samindi De Silva',      role: 'HR Lead' },
  { id: 'akil',    name: 'Akil Fernando',         role: 'Procurement / Review' },
  { id: 'romesh',  name: 'Romesh Wijesiri',       role: 'Leadership' },
  { id: 'rifadha', name: 'Rifadha Azwar',         role: 'Digital Access' },
  { id: 'junaid',  name: 'Junaid Admani',         role: 'Account Manager' },
  { id: 'jude',    name: 'Jude Pottier',          role: 'Account Manager' },
];

const TOOLS = [
  { id: 'teams',      name: 'Microsoft Teams' },
  { id: 'outlook',    name: 'Outlook' },
  { id: 'notion',     name: 'Notion' },
  { id: 'sharepoint', name: 'SharePoint' },
  { id: 'chatgpt',    name: 'Custom GPTs' },
  { id: 'teamtailor', name: 'Teamtailor' },
  { id: 'linkedin',   name: 'LinkedIn' },
  { id: 'hubspot',    name: 'HubSpot' },
  { id: 'dock',       name: 'Dock' },
  { id: 'canva',      name: 'Canva' },
  { id: 'portal',     name: 'TS2 Portal' },
  { id: 'zoho',       name: 'Zoho Recruit' },
];

/* Each workflow:
   - start:   time of day the common path typically begins (display only)
   - steps:   the most-traversed spine (observed path); `dur` = handoff from previous step
   - variants: synthetic alternate traversals
       type 'rework' — back edge from→to (loop)
       type 'detour' — extra steps inserted after `after`, rejoining at `rejoin`
       type 'skip'   — forward edge from→to bypassing steps
*/
const DEPARTMENTS = [
  {
    id: 'hr-ops',
    name: 'HR Operations',
    lead: 'Himaya Gunawardena',
    blurb: 'Onboarding, offboarding and lifecycle execution across the contractor base.',
    workflows: [
      {
        id: 'wf4',
        name: 'Contractor Offboarding',
        code: 'WF4',
        cases: 184,
        start: '09:40',
        desc: 'End-to-end departure: decision, exit call and email, tracker row, channel removal, lifecycle record, device recovery, close-out.',
        people: ['piyara', 'himaya', 'samindi', 'akil'],
        tools: ['teams', 'outlook', 'notion', 'portal'],
        steps: [
          { id: 's1', label: 'Offboarding decision',      owner: 'samindi', tool: 'teams',   dur: null,
            summary: 'The HR lead confirms the departure in the HR-gang Teams channel and names the last working day; this message is what every downstream step keys off.' },
          { id: 's2', label: 'Exit call with contractor', owner: 'piyara',  tool: 'teams',   dur: '2 h',
            summary: 'A 15–20 minute Teams call walks the contractor through returns, final pay timing and access cut-off; notes are typed live into the call chat.' },
          { id: 's3', label: 'Exit email sent',           owner: 'piyara',  tool: 'outlook', dur: '9 m',
            summary: 'The exit template is filled from the call notes and sent from Outlook, cc HR-gang, with the asset-return form attached.' },
          { id: 's4', label: 'Offboarding tracker row',   owner: 'piyara',  tool: 'notion',  dur: '8 m',
            summary: 'A new row is added to the Notion offboarding tracker — name, LWD, device serial, channels — and status set to “In progress”.' },
          { id: 's5', label: 'Channel removal',           owner: 'himaya',  tool: 'teams',   dur: '21 h',
            summary: 'On the morning after LWD the contractor is removed from every client and internal Teams channel, working from the tracker row.' },
          { id: 's6', label: 'Lifecycle record filed',    owner: 'himaya',  tool: 'portal',  dur: '19 m',
            summary: 'The TS2 Portal team-member record is closed with the exit date and reason; the profile flips to “Alumni”.' },
          { id: 's7', label: 'Device recovered',          owner: 'akil',    tool: 'teams',   dur: '7 m',
            summary: 'Procurement confirms the laptop is back in the office (photo of the serial posted to the channel) and marks it ready for wipe.' },
          { id: 's8', label: 'Close-out confirmed',       owner: 'himaya',  tool: 'teams',   dur: '37 m',
            summary: 'A single “✅ offboarded” message in HR-gang closes the case; the tracker row is set to “Complete”.' },
        ],
        variants: [
          { type: 'rework', from: 's2', to: 's1', share: 0.14, label: 'No answer — call retried next day' },
          { type: 'detour', after: 's3', rejoin: 's4', share: 0.11, label: 'Last-working-day correction',
            steps: [{ id: 'x1', label: 'Email date corrected', owner: 'piyara', tool: 'outlook',
              summary: 'The LWD in the exit email was wrong; a corrected email is sent and the original recalled.' }] },
          { type: 'skip',   from: 's4', to: 's6', share: 0.07, label: 'Contractor had no channel access' },
          { type: 'rework', from: 's7', to: 's5', share: 0.05, label: 'Device unreturned — chase loop' },
          { type: 'detour', after: 's6', rejoin: 's7', share: 0.03, label: 'Remote wipe required',
            steps: [{ id: 'x2', label: 'Remote wipe issued', owner: 'himaya', tool: 'portal',
              summary: 'Device could not be recovered in person; a remote wipe is triggered from the portal before close-out.' }] },
        ],
      },
      {
        id: 'wf3',
        name: 'New-Hire Onboarding',
        code: 'WF3',
        cases: 236,
        start: '08:55',
        desc: 'Induction booking, roster entry, laptop procurement, police-clearance funding and confirmation for each new hire.',
        people: ['piyara', 'himaya', 'akil'],
        tools: ['outlook', 'sharepoint', 'teams', 'chatgpt'],
        steps: [
          { id: 's1', label: 'Induction invite issued',    owner: 'piyara', tool: 'outlook',    dur: null,
            summary: 'The signed offer triggers an Outlook calendar invite for the group induction; the hire, their AM and HR-gang are all on it.' },
          { id: 's2', label: 'Roster row created',         owner: 'himaya', tool: 'sharepoint', dur: '22 h',
            summary: 'A row is added to the SharePoint staff roster the next morning — start date, client, seat, device status “Pending”.' },
          { id: 's3', label: 'Laptop procurement raised',  owner: 'himaya', tool: 'teams',      dur: '27 m',
            summary: 'A procurement request is posted to the Ops channel tagging Akil with the spec and start date.' },
          { id: 's4', label: 'Clearance precedent pulled', owner: 'himaya', tool: 'outlook',    dur: '4 m',
            summary: 'A previous police-clearance payment email is found by search and opened as the template for this hire.' },
          { id: 's5', label: 'Payment email drafted',      owner: 'himaya', tool: 'chatgpt',    dur: '3 m',
            summary: 'The precedent is pasted into the HR GPT with the new details; the returned draft is tidied for tone.' },
          { id: 's6', label: 'Finance cc’d + sent',        owner: 'himaya', tool: 'outlook',    dur: '5 m',
            summary: 'The payment instruction goes to the hire with Finance in cc so the clearance fee is reimbursed on the first pay run.' },
          { id: 's7', label: 'Induction held',             owner: 'piyara', tool: 'teams',      dur: '46 h',
            summary: 'A 45-minute Teams induction covers tools, timesheets and client etiquette; attendance is confirmed back in the roster.' },
        ],
        variants: [
          { type: 'rework', from: 's6', to: 's5', share: 0.16, label: 'Draft revised after GPT pass' },
          { type: 'detour', after: 's3', rejoin: 's4', share: 0.09, label: 'Courier option sourced',
            steps: [{ id: 'x1', label: 'Transport quote compared', owner: 'akil', tool: 'teams',
              summary: 'Two courier quotes are posted to the channel so the laptop can reach a remote hire before day one.' }] },
          { type: 'skip',   from: 's2', to: 's4', share: 0.08, label: 'Device already in stock' },
          { type: 'rework', from: 's7', to: 's1', share: 0.04, label: 'Induction rescheduled' },
        ],
      },
      {
        id: 'wf11',
        name: 'Intake & Tracker Maintenance',
        code: 'WF11',
        cases: 312,
        start: '09:05',
        desc: 'Document intake, checklist boards, reference-check table and the pending-work list that keeps every hire moving.',
        people: ['himaya'],
        tools: ['outlook', 'sharepoint', 'notion', 'chatgpt'],
        steps: [
          { id: 's1', label: 'Docs received & acknowledged', owner: 'himaya', tool: 'outlook',    dur: null,
            summary: 'Incoming ID, bank and clearance documents are opened in Outlook and acknowledged with a one-line reply.' },
          { id: 's2', label: 'Roster status updated',        owner: 'himaya', tool: 'sharepoint', dur: '3 m',
            summary: 'The hire’s roster row flips from “Docs pending” to “Docs received”; missing items are noted in the comment column.' },
          { id: 's3', label: 'Checklist board groomed',      owner: 'himaya', tool: 'notion',     dur: '3 m',
            summary: 'Cards on the Notion onboarding checklist board are ticked or moved; blocked cards get a red tag.' },
          { id: 's4', label: 'Pending-work list revised',    owner: 'himaya', tool: 'notion',     dur: '2 m',
            summary: 'The personal “pending” list is re-ordered for the day — chases first, then filing.' },
          { id: 's5', label: 'Reference checks advanced',    owner: 'himaya', tool: 'notion',     dur: '1 m',
            summary: 'Reference-check table rows are updated with responses received overnight; outstanding referees are flagged.' },
          { id: 's6', label: 'Confirmation email polished',  owner: 'himaya', tool: 'chatgpt',    dur: '28 m',
            summary: 'A confirmation-of-documents email is drafted in the HR GPT and edited before sending to the hire.' },
          { id: 's7', label: 'Check-in tracker reviewed',    owner: 'himaya', tool: 'notion',     dur: '58 m',
            summary: 'The 30/60/90-day check-in tracker is scanned for hires due a call this week; calls are booked.' },
        ],
        variants: [
          { type: 'rework', from: 's6', to: 's1', share: 0.18, label: 'Documents incomplete — re-request' },
          { type: 'skip',   from: 's3', to: 's6', share: 0.12, label: 'No reference checks due' },
          { type: 'detour', after: 's5', rejoin: 's6', share: 0.06, label: 'Clearance letter re-addressed',
            steps: [{ id: 'x1', label: 'Police-station detail fixed', owner: 'himaya', tool: 'outlook',
              summary: 'The clearance letter named the wrong station; a corrected letter is re-issued to the hire.' }] },
        ],
      },
    ],
  },
  {
    id: 'compliance',
    name: 'Compliance & ISO',
    lead: 'Piyara Wijekoon',
    blurb: 'ISO-27001 authoring, audit evidence and escalation handling.',
    workflows: [
      {
        id: 'wf1',
        name: 'ISMS Form Authoring',
        code: 'WF1',
        cases: 97,
        start: '10:20',
        desc: 'Offboarding Asset Declaration & Return Form: GPT draft, Word assembly, HR-gang review, ISO reformat, scope debate.',
        people: ['piyara', 'himaya', 'samindi', 'akil'],
        tools: ['chatgpt', 'sharepoint', 'teams'],
        steps: [
          { id: 's1', label: 'Section drafted in ISO GPT',  owner: 'piyara',  tool: 'chatgpt',    dur: null,
            summary: 'The control requirement is pasted into the ISO GPT, which returns a first-pass section in ISMS house style.' },
          { id: 's2', label: 'Form assembled in Word',      owner: 'piyara',  tool: 'sharepoint', dur: '13 m',
            summary: 'Sections are assembled into the Word template on SharePoint — header block, declaration table, signature panel.' },
          { id: 's3', label: 'Wording checked vs SOP-011',  owner: 'piyara',  tool: 'sharepoint', dur: '2 m',
            summary: 'SOP-011 is opened side by side to confirm terminology and clause numbering match.' },
          { id: 's4', label: 'Draft pasted for review',     owner: 'piyara',  tool: 'teams',      dur: '7 m',
            summary: 'The draft link and a short “please review” note are posted to HR-gang.' },
          { id: 's5', label: 'Formatting comments back',    owner: 'samindi', tool: 'teams',      dur: '5 m',
            summary: 'The HR lead replies in-thread with formatting and scope comments, usually within the hour.' },
          { id: 's6', label: 'ISO reformat (FORMAT-016)',   owner: 'samindi', tool: 'sharepoint', dur: '23 h',
            summary: 'The document is re-laid to FORMAT-016 the next day — document control table, revision history, footer codes.' },
          { id: 's7', label: 'Reviewer sign-off',           owner: 'akil',    tool: 'teams',      dur: '4 h',
            summary: 'The independent reviewer confirms sign-off in the channel and the form is moved to the Approved library.' },
        ],
        variants: [
          { type: 'rework', from: 's5', to: 's2', share: 0.21, label: 'Alignment fixes requested' },
          { type: 'detour', after: 's4', rejoin: 's5', share: 0.09, label: 'Access problem on the doc',
            steps: [{ id: 'x1', label: 'Share permissions repaired', owner: 'piyara', tool: 'sharepoint',
              summary: 'Reviewers could not open the link; sharing is widened to the HR group and the link re-posted.' }] },
          { type: 'rework', from: 's7', to: 's6', share: 0.07, label: 'Terminology change ("employee")' },
          { type: 'skip',   from: 's3', to: 's6', share: 0.04, label: 'Minor edit — straight to reformat' },
        ],
      },
      {
        id: 'wf5',
        name: 'Audit Evidence Collection',
        code: 'WF5',
        cases: 143,
        start: '09:30',
        desc: 'LMS completion chasing, policy walkthroughs, evidence attachment and re-attachment for the live ISO-27001 audit.',
        people: ['piyara', 'himaya'],
        tools: ['teams', 'outlook', 'sharepoint'],
        steps: [
          { id: 's1', label: 'Evidence item identified',   owner: 'piyara', tool: 'teams',      dur: null,
            summary: 'An open item on the auditor’s evidence list is picked from the audit channel and assigned.' },
          { id: 's2', label: 'Owner chased for completion',owner: 'piyara', tool: 'teams',      dur: '11 m',
            summary: 'The control owner is pinged directly with the LMS module or policy that still needs completing.' },
          { id: 's3', label: 'Policy walkthrough on call', owner: 'piyara', tool: 'teams',      dur: '1 h',
            summary: 'A short call walks the owner through the policy so the acknowledgement is informed, not a click-through.' },
          { id: 's4', label: 'Evidence attached to thread',owner: 'himaya', tool: 'outlook',    dur: '22 h',
            summary: 'Completion screenshots and the signed acknowledgement are attached to the auditor email thread.' },
          { id: 's5', label: 'Attachment verified',        owner: 'himaya', tool: 'outlook',    dur: '1 m',
            summary: 'The sent item is reopened to confirm every attachment uploaded correctly.' },
          { id: 's6', label: 'Filed for auditor',          owner: 'piyara', tool: 'sharepoint', dur: '3 h',
            summary: 'Evidence is copied into the numbered SharePoint audit folder and the tracker row set to “Provided”.' },
        ],
        variants: [
          { type: 'rework', from: 's5', to: 's4', share: 0.19, label: 'Attachment failed — re-upload' },
          { type: 'rework', from: 's2', to: 's2', share: 0.13, label: 'Repeat chase (no response)' },
          { type: 'detour', after: 's1', rejoin: 's2', share: 0.08, label: 'Archived profile recovered',
            steps: [{ id: 'x1', label: 'Archived record restored', owner: 'himaya', tool: 'portal',
              summary: 'The owner had been archived in the portal; the record is restored so LMS history can be pulled.' }] },
          { type: 'skip',   from: 's2', to: 's4', share: 0.10, label: 'Already complete — evidence only' },
        ],
      },
      {
        id: 'wf10',
        name: 'Client Escalation Handling',
        code: 'WF10',
        cases: 41,
        start: '11:10',
        desc: 'Working-hours complaint traced from client email, through leadership escalation, to evidence review and check-in note.',
        people: ['piyara', 'samindi', 'romesh'],
        tools: ['portal', 'outlook', 'teams'],
        steps: [
          { id: 's1', label: 'Escalation email surfaced', owner: 'romesh',  tool: 'outlook', dur: null,
            summary: 'A client complaint about a contractor’s hours lands with leadership and is forwarded to HR with a one-line ask.' },
          { id: 's2', label: 'HR profile pulled',         owner: 'piyara',  tool: 'portal',  dur: '2 m',
            summary: 'The contractor’s portal profile — client, start date, previous notes — is opened to frame the case.' },
          { id: 's3', label: 'Leadership call',           owner: 'samindi', tool: 'teams',   dur: '27 m',
            summary: 'A 10-minute call agrees the stance and who speaks to the client and to the contractor.' },
          { id: 's4', label: 'Evidence search run',       owner: 'piyara',  tool: 'teams',   dur: '3 m',
            summary: 'Teams activity and timesheet messages are searched for the dates in question.' },
          { id: 's5', label: 'Check-in note logged',      owner: 'piyara',  tool: 'teams',   dur: '5 m',
            summary: 'The outcome and next check-in date are logged as a note in the HR channel thread.' },
        ],
        variants: [
          { type: 'rework', from: 's4', to: 's3', share: 0.15, label: 'Second call after evidence' },
          { type: 'skip',   from: 's2', to: 's4', share: 0.09, label: 'Known case — straight to evidence' },
          { type: 'detour', after: 's5', rejoin: null, share: 0.06, label: 'Client follow-up sent',
            steps: [{ id: 'x1', label: 'Client reassurance email', owner: 'samindi', tool: 'outlook',
              summary: 'A reassurance email summarising the action taken is sent to the client contact.' }] },
        ],
      },
    ],
  },
  {
    id: 'talent',
    name: 'Talent Acquisition',
    lead: 'Zolara Peiris',
    blurb: 'Requisitions, sourcing, screening and client-facing candidate pitches.',
    workflows: [
      {
        id: 'wf8',
        name: 'Candidate Slate → Client Pitch',
        code: 'WF8',
        cases: 128,
        start: '09:15',
        desc: 'From Notion deal card through CV parsing, Dock pitch assembly, Canva one-pagers, to the Proposals & Profiles share.',
        people: ['zolara', 'junaid'],
        tools: ['notion', 'chatgpt', 'dock', 'canva', 'teams'],
        steps: [
          { id: 's1', label: 'Deal card opened (Urgent)', owner: 'zolara', tool: 'notion',  dur: null,
            summary: 'An “Urgent” deal card in the Notion pipeline is opened; role, client and rate band are read off.' },
          { id: 's2', label: 'CV parsed by CVGPT',        owner: 'zolara', tool: 'chatgpt', dur: '2 m',
            summary: 'Shortlisted CVs are dropped into CVGPT, which returns a normalised profile block per candidate.' },
          { id: 's3', label: 'Dock pitch assembled',      owner: 'zolara', tool: 'dock',    dur: '1 m',
            summary: 'A Dock pitch page is cloned from the template and the profile blocks pasted in.' },
          { id: 's4', label: 'Canva one-pagers built',    owner: 'zolara', tool: 'canva',   dur: '1 m',
            summary: 'Each candidate gets a branded one-pager in Canva, exported as PDF and attached to the Dock.' },
          { id: 's5', label: 'Rates & availability set',  owner: 'zolara', tool: 'dock',    dur: '1 m',
            summary: 'TS rate, candidate availability and notice period are filled into the pitch table.' },
          { id: 's6', label: 'Dock shared to channel',    owner: 'zolara', tool: 'teams',   dur: '3 m',
            summary: 'The Dock link is posted to Proposals & Profiles for the AM to send on.' },
          { id: 's7', label: 'AM tagged on deal',         owner: 'zolara', tool: 'notion',  dur: '1 m',
            summary: 'The AM is tagged on the deal card and the stage moves to “Pitched”.' },
        ],
        variants: [
          { type: 'rework', from: 's5', to: 's3', share: 0.17, label: 'Candidate removed from pitch' },
          { type: 'detour', after: 's5', rejoin: 's6', share: 0.12, label: 'Missing TS rate chased',
            steps: [{ id: 'x1', label: 'Rate request to AM', owner: 'zolara', tool: 'notion',
              summary: 'No TS rate on the card; the AM is asked in a card comment and the pitch waits.' }] },
          { type: 'rework', from: 's4', to: 's2', share: 0.08, label: 'Profile re-parsed for detail' },
          { type: 'skip',   from: 's3', to: 's6', share: 0.05, label: 'One-pagers reused from prior deal' },
        ],
      },
      {
        id: 'wf9',
        name: 'Role Repost & Sourcing',
        code: 'WF9',
        cases: 156,
        start: '08:45',
        desc: 'Closed role reposted, promoted with budget uplift, cross-ATS sourcing in Zoho, CV screening, Teamtailor import.',
        people: ['zolara', 'jude'],
        tools: ['linkedin', 'teamtailor', 'zoho', 'chatgpt', 'notion'],
        steps: [
          { id: 's1', label: 'Closed role identified',    owner: 'zolara', tool: 'linkedin',   dur: null,
            summary: 'A LinkedIn job post that has auto-closed is spotted in the recruiter dashboard.' },
          { id: 's2', label: 'JD drafted by JDBuilder',   owner: 'zolara', tool: 'chatgpt',    dur: '18 m',
            summary: 'The old JD is refreshed through JDBuilder — new title variants, updated must-haves.' },
          { id: 's3', label: 'Post republished',          owner: 'zolara', tool: 'linkedin',   dur: '1 m',
            summary: 'The role is reposted as a fresh listing so it re-enters the LinkedIn feed.' },
          { id: 's4', label: 'Promotion budget raised',   owner: 'zolara', tool: 'linkedin',   dur: '1 m',
            summary: 'Daily promotion budget is increased for the first 72 hours of the repost.' },
          { id: 's5', label: 'Cross-ATS sourcing sweep',  owner: 'zolara', tool: 'zoho',       dur: '2 h',
            summary: 'Zoho Recruit is searched for past applicants matching the refreshed JD; a shortlist is exported.' },
          { id: 's6', label: 'CV screening run',          owner: 'zolara', tool: 'teamtailor', dur: '3 m',
            summary: 'New applicants are screened in Teamtailor against the must-haves and staged.' },
          { id: 's7', label: 'Candidates imported',       owner: 'zolara', tool: 'teamtailor', dur: '3 m',
            summary: 'The Zoho shortlist is imported into the Teamtailor pipeline with a source tag.' },
          { id: 's8', label: 'Rate check with AM',        owner: 'jude',   tool: 'notion',     dur: '2 m',
            summary: 'The AM confirms the client rate band on the deal card before outreach begins.' },
        ],
        variants: [
          { type: 'rework', from: 's6', to: 's5', share: 0.22, label: 'Sourcing widened — thin pipeline' },
          { type: 'detour', after: 's5', rejoin: 's6', share: 0.10, label: 'FX conversion run for quotes',
            steps: [{ id: 'x1', label: 'Currency lookups (8×)', owner: 'zolara', tool: 'linkedin',
              summary: 'Candidate salary expectations in several currencies are converted to AUD in a browser tab.' }] },
          { type: 'skip',   from: 's3', to: 's5', share: 0.07, label: 'No promotion — organic only' },
          { type: 'rework', from: 's8', to: 's7', share: 0.05, label: 'Import notes revised' },
        ],
      },
    ],
  },
  {
    id: 'marketing',
    name: 'Marketing & Rev Ops',
    lead: 'Jerome Verallo',
    blurb: 'Paid-ads integrity, lead-pipeline audits and recruitment data automation.',
    workflows: [
      {
        id: 'wf6',
        name: 'Lead-Sync Investigation',
        code: 'WF6',
        cases: 62,
        start: '10:05',
        desc: 'Meta → HubSpot audit: integration check, permissions blocker, live-call escalation, reconciliation, written conclusion.',
        people: ['jerome', 'rifadha', 'romesh'],
        tools: ['chatgpt', 'hubspot', 'teams'],
        steps: [
          { id: 's1', label: 'Audit thread opened',        owner: 'jerome',  tool: 'chatgpt', dur: null,
            summary: 'A new GPT thread is started with the lead-count discrepancy and the date range to investigate.' },
          { id: 's2', label: 'Integration details pulled', owner: 'jerome',  tool: 'hubspot', dur: '4 m',
            summary: 'The Meta → HubSpot integration page is opened; sync status and last-run timestamps are copied out.' },
          { id: 's3', label: 'Blocker diagnosed (access)', owner: 'jerome',  tool: 'chatgpt', dur: '5 m',
            summary: 'The GPT narrows the cause to a missing ad-account permission on the connected user.' },
          { id: 's4', label: 'Escalated with screenshot',  owner: 'jerome',  tool: 'teams',   dur: '1 m',
            summary: 'A screenshot of the permission error is posted to Digital Access with the ask.' },
          { id: 's5', label: 'Live call to unblock',       owner: 'rifadha', tool: 'teams',   dur: '17 m',
            summary: 'A screen-share call grants the permission on the org ad account.' },
          { id: 's6', label: 'Access granted — rerun',     owner: 'jerome',  tool: 'chatgpt', dur: '17 m',
            summary: 'The sync is re-triggered and the GPT thread updated with the new run.' },
          { id: 's7', label: 'Counts reconciled',          owner: 'jerome',  tool: 'hubspot', dur: '2 m',
            summary: 'Meta lead count and HubSpot contact count are compared for the window; the gap closes.' },
          { id: 's8', label: 'Conclusion written up',      owner: 'jerome',  tool: 'chatgpt', dur: '11 m',
            summary: 'A short root-cause note is drafted and posted to leadership.' },
        ],
        variants: [
          { type: 'rework', from: 's7', to: 's6', share: 0.14, label: 'Spot-check on flagged lead' },
          { type: 'detour', after: 's4', rejoin: 's5', share: 0.10, label: 'Personal-account request declined',
            steps: [{ id: 'x1', label: 'Org-account alternative agreed', owner: 'rifadha', tool: 'teams',
              summary: 'Access on a personal account is refused; the org account route is agreed in-thread.' }] },
          { type: 'skip',   from: 's3', to: 's6', share: 0.06, label: 'Access already held' },
        ],
      },
      {
        id: 'wf7',
        name: 'LinkedIn Master Workbook',
        code: 'WF7',
        cases: 48,
        start: '09:00',
        desc: 'Weekly rebuild: recruiter exports staged, scheduled agent run, USD conversion, duplicate flags, confirmation gate, upload.',
        people: ['jerome', 'zolara'],
        tools: ['sharepoint', 'chatgpt', 'linkedin'],
        steps: [
          { id: 's1', label: 'Recruiter exports staged',  owner: 'zolara', tool: 'sharepoint', dur: null,
            summary: 'Each recruiter drops their weekly LinkedIn CSV export into the Uploads folder.' },
          { id: 's2', label: 'Uploads folder verified',   owner: 'jerome', tool: 'sharepoint', dur: '10 m',
            summary: 'The folder is checked for one file per recruiter and the right week in the filename.' },
          { id: 's3', label: 'Validation policy applied', owner: 'jerome', tool: 'chatgpt',    dur: '5 m',
            summary: 'The validation policy is pasted into the workbook agent — required columns, currency rules.' },
          { id: 's4', label: 'Agent run executed',        owner: 'jerome', tool: 'chatgpt',    dur: '26 m',
            summary: 'The agent merges the exports, converts to USD and flags duplicate Job IDs.' },
          { id: 's5', label: 'Master workbook rebuilt',   owner: 'jerome', tool: 'sharepoint', dur: '8 m',
            summary: 'The output replaces last week’s master workbook; pivots refresh.' },
          { id: 's6', label: 'Confirmation gate passed',  owner: 'jerome', tool: 'chatgpt',    dur: '2 m',
            summary: 'Row counts and totals are read back and confirmed before publishing.' },
          { id: 's7', label: 'Uploaded to library',       owner: 'jerome', tool: 'sharepoint', dur: '6 m',
            summary: 'The workbook is uploaded to the Reports library and the link posted to leadership.' },
        ],
        variants: [
          { type: 'rework', from: 's4', to: 's2', share: 0.16, label: 'Missing export — recruiter chased' },
          { type: 'detour', after: 's4', rejoin: 's5', share: 0.11, label: 'FX data gap flagged',
            steps: [{ id: 'x1', label: 'Manual FX rate supplied', owner: 'jerome', tool: 'chatgpt',
              summary: 'The FX feed lacked one currency; the rate is looked up and supplied to the agent by hand.' }] },
          { type: 'rework', from: 's6', to: 's4', share: 0.08, label: 'Duplicates re-keyed on Job ID' },
        ],
      },
    ],
  },
  {
    id: 'welfare',
    name: 'People & Welfare',
    lead: 'Samindi De Silva',
    blurb: 'Staff welfare, relief coordination and cross-team care decisions.',
    workflows: [
      {
        id: 'wf2',
        name: 'Relief & Gift Coordination',
        code: 'WF2',
        cases: 34,
        start: '13:20',
        desc: 'Typhoon-relief support: options researched, hamper vs cash debated, budget escalated, policy check, sourcing handed off.',
        people: ['jerome', 'himaya', 'samindi', 'romesh'],
        tools: ['teams', 'portal'],
        steps: [
          { id: 's1', label: 'Affected staff identified',  owner: 'jerome',  tool: 'chatgpt', dur: null,
            summary: 'Staff in the affected region are listed by asking the HR GPT to filter the roster by location.' },
          { id: 's2', label: 'Gift options researched',    owner: 'jerome',  tool: 'teams',   dur: '5 m',
            summary: 'Local hamper and voucher options are gathered into a short Teams message with prices.' },
          { id: 's3', label: 'Option shared 1:1',          owner: 'jerome',  tool: 'teams',   dur: '1 m',
            summary: 'The preferred option is shared with the HR lead in a direct message.' },
          { id: 's4', label: 'Cost estimated (AUD)',       owner: 'himaya',  tool: 'teams',   dur: '2 m',
            summary: 'Per-person cost is multiplied out and converted to AUD in the thread.' },
          { id: 's5', label: 'Escalated to HR gang',       owner: 'himaya',  tool: 'teams',   dur: '7 m',
            summary: 'The total is posted to HR-gang for a budget decision.' },
          { id: 's6', label: 'Policy ruling (no cash)',    owner: 'samindi', tool: 'teams',   dur: '7 m',
            summary: 'The HR lead rules that gifts must be in kind, not cash, citing the welfare policy.' },
          { id: 's7', label: 'Sourcing handed back',       owner: 'jerome',  tool: 'teams',   dur: '5 m',
            summary: 'Sourcing the hampers is handed back to marketing ops with the approved budget.' },
        ],
        variants: [
          { type: 'rework', from: 's4', to: 's2', share: 0.18, label: 'Hamper vs cash re-debated' },
          { type: 'detour', after: 's5', rejoin: 's6', share: 0.09, label: 'Record verified in portal',
            steps: [{ id: 'x1', label: 'Team-member record checked', owner: 'himaya', tool: 'portal',
              summary: 'A staff member’s location is double-checked against their portal record before inclusion.' }] },
          { type: 'skip',   from: 's3', to: 's5', share: 0.06, label: 'Cost known — straight to HR gang' },
        ],
      },
    ],
  },
];

export const ATLAS = { departments: DEPARTMENTS, people: PEOPLE, tools: TOOLS };
