/* ============================================================
   LEX OPS — Process Atlas · Teams Squared
   Data model: departments → workflows → spine steps + variants
   Spine steps are drawn from the observed AW+screenshot
   transcripts (candidate_workflows_screenshots.md).
   Variant traversal counts are synthetic for the demo.
   ============================================================ */

const PEOPLE = [
  { id: 'piyara',  name: 'Piyara Wijekoon',      role: 'HR Mgmt / ISO Compliance' },
  { id: 'himaya',  name: 'Himaya Gunawardena',    role: 'HR Operations Specialist' },
  { id: 'jerome',  name: 'Jerome Verallo',        role: 'Marketing Ops / Rec. Data' },
  { id: 'zolara',  name: 'Zolara Peiris',         role: 'Talent Acquisition' },
  { id: 'samindi', name: 'Samindi De Silva',      role: 'HR Lead' },
  { id: 'akil',    name: 'Akil Fernando',         role: 'Procurement / Review' },
  { id: 'romesh',  name: 'Romesh Wijesiri',       role: 'Leadership' },
  { id: 'rifadha', name: 'Rifadha Azwar',         role: 'Digital Access' },
  { id: 'junaid',  name: 'Junaid Admani',         role: 'Account Manager' },
  { id: 'jude',    name: 'Jude Pottier',          role: 'Account Manager' },
];

const TOOLS = [
  { id: 'teams',      name: 'Microsoft Teams' },
  { id: 'outlook',    name: 'Outlook' },
  { id: 'notion',     name: 'Notion' },
  { id: 'sharepoint', name: 'SharePoint' },
  { id: 'chatgpt',    name: 'Custom GPTs' },
  { id: 'teamtailor', name: 'Teamtailor' },
  { id: 'linkedin',   name: 'LinkedIn' },
  { id: 'hubspot',    name: 'HubSpot' },
  { id: 'dock',       name: 'Dock' },
  { id: 'canva',      name: 'Canva' },
  { id: 'portal',     name: 'TS2 Portal' },
  { id: 'zoho',       name: 'Zoho Recruit' },
];

/* Each workflow:
   - steps:   the most-traversed spine (observed path)
   - dur:     handoff time from previous step (display only)
   - variants: synthetic alternate traversals
       type 'rework' — back edge from→to (loop)
       type 'detour' — extra steps inserted after `after`, rejoining at `rejoin`
       type 'skip'   — forward edge from→to bypassing steps
*/
const DEPARTMENTS = [
  {
    id: 'hr-ops',
    name: 'HR Operations',
    lead: 'Himaya Gunawardena',
    blurb: 'Onboarding, offboarding and lifecycle execution across the contractor base.',
    workflows: [
      {
        id: 'wf4',
        name: 'Contractor Offboarding',
        code: 'WF4',
        cases: 184,
        desc: 'End-to-end departure: decision, exit call and email, tracker row, channel removal, lifecycle record, device recovery, close-out.',
        people: ['piyara', 'himaya', 'samindi', 'akil'],
        tools: ['teams', 'outlook', 'notion', 'portal'],
        steps: [
          { id: 's1', label: 'Offboarding decision',      owner: 'samindi', tool: 'teams',   dur: null },
          { id: 's2', label: 'Exit call with contractor', owner: 'piyara',  tool: 'teams',   dur: '2 h' },
          { id: 's3', label: 'Exit email sent',           owner: 'piyara',  tool: 'outlook', dur: '9 m' },
          { id: 's4', label: 'Offboarding tracker row',   owner: 'piyara',  tool: 'notion',  dur: '8 m' },
          { id: 's5', label: 'Channel removal',           owner: 'himaya',  tool: 'teams',   dur: '21 h' },
          { id: 's6', label: 'Lifecycle record filed',    owner: 'himaya',  tool: 'portal',  dur: '19 m' },
          { id: 's7', label: 'Device recovered',          owner: 'akil',    tool: 'teams',   dur: '7 m' },
          { id: 's8', label: 'Close-out confirmed',       owner: 'himaya',  tool: 'teams',   dur: '37 m' },
        ],
        variants: [
          { type: 'rework', from: 's2', to: 's1', share: 0.14, label: 'No answer — call retried next day' },
          { type: 'detour', after: 's3', rejoin: 's4', share: 0.11, label: 'Last-working-day correction',
            steps: [{ id: 'x1', label: 'Email date corrected', owner: 'piyara', tool: 'outlook' }] },
          { type: 'skip',   from: 's4', to: 's6', share: 0.07, label: 'Contractor had no channel access' },
          { type: 'rework', from: 's7', to: 's5', share: 0.05, label: 'Device unreturned — chase loop' },
          { type: 'detour', after: 's6', rejoin: 's7', share: 0.03, label: 'Remote wipe required',
            steps: [{ id: 'x2', label: 'Remote wipe issued', owner: 'himaya', tool: 'portal' }] },
        ],
      },
      {
        id: 'wf3',
        name: 'New-Hire Onboarding',
        code: 'WF3',
        cases: 236,
        desc: 'Induction booking, roster entry, laptop procurement, police-clearance funding and confirmation for each new hire.',
        people: ['piyara', 'himaya', 'akil'],
        tools: ['outlook', 'sharepoint', 'teams', 'chatgpt'],
        steps: [
          { id: 's1', label: 'Induction invite issued',    owner: 'piyara', tool: 'outlook',    dur: null },
          { id: 's2', label: 'Roster row created',         owner: 'himaya', tool: 'sharepoint', dur: '22 h' },
          { id: 's3', label: 'Laptop procurement raised',  owner: 'himaya', tool: 'teams',      dur: '27 m' },
          { id: 's4', label: 'Clearance precedent pulled', owner: 'himaya', tool: 'outlook',    dur: '4 m' },
          { id: 's5', label: 'Payment email drafted',      owner: 'himaya', tool: 'chatgpt',    dur: '3 m' },
          { id: 's6', label: 'Finance cc’d + sent',        owner: 'himaya', tool: 'outlook',    dur: '5 m' },
          { id: 's7', label: 'Induction held',             owner: 'piyara', tool: 'teams',      dur: '46 h' },
        ],
        variants: [
          { type: 'rework', from: 's6', to: 's5', share: 0.16, label: 'Draft revised after GPT pass' },
          { type: 'detour', after: 's3', rejoin: 's4', share: 0.09, label: 'Courier option sourced',
            steps: [{ id: 'x1', label: 'Transport quote compared', owner: 'akil', tool: 'teams' }] },
          { type: 'skip',   from: 's2', to: 's4', share: 0.08, label: 'Device already in stock' },
          { type: 'rework', from: 's7', to: 's1', share: 0.04, label: 'Induction rescheduled' },
        ],
      },
      {
        id: 'wf11',
        name: 'Intake & Tracker Maintenance',
        code: 'WF11',
        cases: 312,
        desc: 'Document intake, checklist boards, reference-check table and the pending-work list that keeps every hire moving.',
        people: ['himaya'],
        tools: ['outlook', 'sharepoint', 'notion', 'chatgpt'],
        steps: [
          { id: 's1', label: 'Docs received & acknowledged', owner: 'himaya', tool: 'outlook',    dur: null },
          { id: 's2', label: 'Roster status updated',        owner: 'himaya', tool: 'sharepoint', dur: '3 m' },
          { id: 's3', label: 'Checklist board groomed',      owner: 'himaya', tool: 'notion',     dur: '3 m' },
          { id: 's4', label: 'Pending-work list revised',    owner: 'himaya', tool: 'notion',     dur: '2 m' },
          { id: 's5', label: 'Reference checks advanced',    owner: 'himaya', tool: 'notion',     dur: '1 m' },
          { id: 's6', label: 'Confirmation email polished',  owner: 'himaya', tool: 'chatgpt',    dur: '28 m' },
          { id: 's7', label: 'Check-in tracker reviewed',    owner: 'himaya', tool: 'notion',     dur: '58 m' },
        ],
        variants: [
          { type: 'rework', from: 's6', to: 's1', share: 0.18, label: 'Documents incomplete — re-request' },
          { type: 'skip',   from: 's3', to: 's6', share: 0.12, label: 'No reference checks due' },
          { type: 'detour', after: 's5', rejoin: 's6', share: 0.06, label: 'Clearance letter re-addressed',
            steps: [{ id: 'x1', label: 'Police-station detail fixed', owner: 'himaya', tool: 'outlook' }] },
        ],
      },
    ],
  },
  {
    id: 'compliance',
    name: 'Compliance & ISO',
    lead: 'Piyara Wijekoon',
    blurb: 'ISO-27001 authoring, audit evidence and escalation handling.',
    workflows: [
      {
        id: 'wf1',
        name: 'ISMS Form Authoring',
        code: 'WF1',
        cases: 97,
        desc: 'Offboarding Asset Declaration & Return Form: GPT draft, Word assembly, HR-gang review, ISO reformat, scope debate.',
        people: ['piyara', 'himaya', 'samindi', 'akil'],
        tools: ['chatgpt', 'sharepoint', 'teams'],
        steps: [
          { id: 's1', label: 'Section drafted in ISO GPT',  owner: 'piyara',  tool: 'chatgpt',    dur: null },
          { id: 's2', label: 'Form assembled in Word',      owner: 'piyara',  tool: 'sharepoint', dur: '13 m' },
          { id: 's3', label: 'Wording checked vs SOP-011',  owner: 'piyara',  tool: 'sharepoint', dur: '2 m' },
          { id: 's4', label: 'Draft pasted for review',     owner: 'piyara',  tool: 'teams',      dur: '7 m' },
          { id: 's5', label: 'Formatting comments back',    owner: 'samindi', tool: 'teams',      dur: '5 m' },
          { id: 's6', label: 'ISO reformat (FORMAT-016)',   owner: 'samindi', tool: 'sharepoint', dur: '23 h' },
          { id: 's7', label: 'Reviewer sign-off',           owner: 'akil',    tool: 'teams',      dur: '4 h' },
        ],
        variants: [
          { type: 'rework', from: 's5', to: 's2', share: 0.21, label: 'Alignment fixes requested' },
          { type: 'detour', after: 's4', rejoin: 's5', share: 0.09, label: 'Access problem on the doc',
            steps: [{ id: 'x1', label: 'Share permissions repaired', owner: 'piyara', tool: 'sharepoint' }] },
          { type: 'rework', from: 's7', to: 's6', share: 0.07, label: 'Terminology change ("employee")' },
          { type: 'skip',   from: 's3', to: 's6', share: 0.04, label: 'Minor edit — straight to reformat' },
        ],
      },
      {
        id: 'wf5',
        name: 'Audit Evidence Collection',
        code: 'WF5',
        cases: 143,
        desc: 'LMS completion chasing, policy walkthroughs, evidence attachment and re-attachment for the live ISO-27001 audit.',
        people: ['piyara', 'himaya'],
        tools: ['teams', 'outlook', 'sharepoint'],
        steps: [
          { id: 's1', label: 'Evidence item identified',   owner: 'piyara', tool: 'teams',      dur: null },
          { id: 's2', label: 'Owner chased for completion',owner: 'piyara', tool: 'teams',      dur: '11 m' },
          { id: 's3', label: 'Policy walkthrough on call', owner: 'piyara', tool: 'teams',      dur: '1 h' },
          { id: 's4', label: 'Evidence attached to thread',owner: 'himaya', tool: 'outlook',    dur: '22 h' },
          { id: 's5', label: 'Attachment verified',        owner: 'himaya', tool: 'outlook',    dur: '1 m' },
          { id: 's6', label: 'Filed for auditor',          owner: 'piyara', tool: 'sharepoint', dur: '3 h' },
        ],
        variants: [
          { type: 'rework', from: 's5', to: 's4', share: 0.19, label: 'Attachment failed — re-upload' },
          { type: 'rework', from: 's2', to: 's2', share: 0.13, label: 'Repeat chase (no response)' },
          { type: 'detour', after: 's1', rejoin: 's2', share: 0.08, label: 'Archived profile recovered',
            steps: [{ id: 'x1', label: 'Archived record restored', owner: 'himaya', tool: 'portal' }] },
          { type: 'skip',   from: 's2', to: 's4', share: 0.10, label: 'Already complete — evidence only' },
        ],
      },
      {
        id: 'wf10',
        name: 'Client Escalation Handling',
        code: 'WF10',
        cases: 41,
        desc: 'Working-hours complaint traced from client email, through leadership escalation, to evidence review and check-in note.',
        people: ['piyara', 'samindi', 'romesh'],
        tools: ['portal', 'outlook', 'teams'],
        steps: [
          { id: 's1', label: 'Escalation email surfaced', owner: 'romesh',  tool: 'outlook', dur: null },
          { id: 's2', label: 'HR profile pulled',         owner: 'piyara',  tool: 'portal',  dur: '2 m' },
          { id: 's3', label: 'Leadership call',           owner: 'samindi', tool: 'teams',   dur: '27 m' },
          { id: 's4', label: 'Evidence search run',       owner: 'piyara',  tool: 'teams',   dur: '3 m' },
          { id: 's5', label: 'Check-in note logged',      owner: 'piyara',  tool: 'teams',   dur: '5 m' },
        ],
        variants: [
          { type: 'rework', from: 's4', to: 's3', share: 0.15, label: 'Second call after evidence' },
          { type: 'skip',   from: 's2', to: 's4', share: 0.09, label: 'Known case — straight to evidence' },
          { type: 'detour', after: 's5', rejoin: null, share: 0.06, label: 'Client follow-up sent',
            steps: [{ id: 'x1', label: 'Client reassurance email', owner: 'samindi', tool: 'outlook' }] },
        ],
      },
    ],
  },
  {
    id: 'talent',
    name: 'Talent Acquisition',
    lead: 'Zolara Peiris',
    blurb: 'Requisitions, sourcing, screening and client-facing candidate pitches.',
    workflows: [
      {
        id: 'wf8',
        name: 'Candidate Slate → Client Pitch',
        code: 'WF8',
        cases: 128,
        desc: 'From Notion deal card through CV parsing, Dock pitch assembly, Canva one-pagers, to the Proposals & Profiles share.',
        people: ['zolara', 'junaid'],
        tools: ['notion', 'chatgpt', 'dock', 'canva', 'teams'],
        steps: [
          { id: 's1', label: 'Deal card opened (Urgent)', owner: 'zolara', tool: 'notion',  dur: null },
          { id: 's2', label: 'CV parsed by CVGPT',        owner: 'zolara', tool: 'chatgpt', dur: '2 m' },
          { id: 's3', label: 'Dock pitch assembled',      owner: 'zolara', tool: 'dock',    dur: '1 m' },
          { id: 's4', label: 'Canva one-pagers built',    owner: 'zolara', tool: 'canva',   dur: '1 m' },
          { id: 's5', label: 'Rates & availability set',  owner: 'zolara', tool: 'dock',    dur: '1 m' },
          { id: 's6', label: 'Dock shared to channel',    owner: 'zolara', tool: 'teams',   dur: '3 m' },
          { id: 's7', label: 'AM tagged on deal',         owner: 'zolara', tool: 'notion',  dur: '1 m' },
        ],
        variants: [
          { type: 'rework', from: 's5', to: 's3', share: 0.17, label: 'Candidate removed from pitch' },
          { type: 'detour', after: 's5', rejoin: 's6', share: 0.12, label: 'Missing TS rate chased',
            steps: [{ id: 'x1', label: 'Rate request to AM', owner: 'zolara', tool: 'notion' }] },
          { type: 'rework', from: 's4', to: 's2', share: 0.08, label: 'Profile re-parsed for detail' },
          { type: 'skip',   from: 's3', to: 's6', share: 0.05, label: 'One-pagers reused from prior deal' },
        ],
      },
      {
        id: 'wf9',
        name: 'Role Repost & Sourcing',
        code: 'WF9',
        cases: 156,
        desc: 'Closed role reposted, promoted with budget uplift, cross-ATS sourcing in Zoho, CV screening, Teamtailor import.',
        people: ['zolara', 'jude'],
        tools: ['linkedin', 'teamtailor', 'zoho', 'chatgpt', 'notion'],
        steps: [
          { id: 's1', label: 'Closed role identified',    owner: 'zolara', tool: 'linkedin',   dur: null },
          { id: 's2', label: 'JD drafted by JDBuilder',   owner: 'zolara', tool: 'chatgpt',    dur: '18 m' },
          { id: 's3', label: 'Post republished',          owner: 'zolara', tool: 'linkedin',   dur: '1 m' },
          { id: 's4', label: 'Promotion budget raised',   owner: 'zolara', tool: 'linkedin',   dur: '1 m' },
          { id: 's5', label: 'Cross-ATS sourcing sweep',  owner: 'zolara', tool: 'zoho',       dur: '2 h' },
          { id: 's6', label: 'CV screening run',          owner: 'zolara', tool: 'teamtailor', dur: '3 m' },
          { id: 's7', label: 'Candidates imported',       owner: 'zolara', tool: 'teamtailor', dur: '3 m' },
          { id: 's8', label: 'Rate check with AM',        owner: 'jude',   tool: 'notion',     dur: '2 m' },
        ],
        variants: [
          { type: 'rework', from: 's6', to: 's5', share: 0.22, label: 'Sourcing widened — thin pipeline' },
          { type: 'detour', after: 's5', rejoin: 's6', share: 0.10, label: 'FX conversion run for quotes',
            steps: [{ id: 'x1', label: 'Currency lookups (8×)', owner: 'zolara', tool: 'linkedin' }] },
          { type: 'skip',   from: 's3', to: 's5', share: 0.07, label: 'No promotion — organic only' },
          { type: 'rework', from: 's8', to: 's7', share: 0.05, label: 'Import notes revised' },
        ],
      },
    ],
  },
  {
    id: 'marketing',
    name: 'Marketing & Rev Ops',
    lead: 'Jerome Verallo',
    blurb: 'Paid-ads integrity, lead-pipeline audits and recruitment data automation.',
    workflows: [
      {
        id: 'wf6',
        name: 'Lead-Sync Investigation',
        code: 'WF6',
        cases: 62,
        desc: 'Meta → HubSpot audit: integration check, permissions blocker, live-call escalation, reconciliation, written conclusion.',
        people: ['jerome', 'rifadha', 'romesh'],
        tools: ['chatgpt', 'hubspot', 'teams'],
        steps: [
          { id: 's1', label: 'Audit thread opened',        owner: 'jerome',  tool: 'chatgpt', dur: null },
          { id: 's2', label: 'Integration details pulled', owner: 'jerome',  tool: 'hubspot', dur: '4 m' },
          { id: 's3', label: 'Blocker diagnosed (access)', owner: 'jerome',  tool: 'chatgpt', dur: '5 m' },
          { id: 's4', label: 'Escalated with screenshot',  owner: 'jerome',  tool: 'teams',   dur: '1 m' },
          { id: 's5', label: 'Live call to unblock',       owner: 'rifadha', tool: 'teams',   dur: '17 m' },
          { id: 's6', label: 'Access granted — rerun',     owner: 'jerome',  tool: 'chatgpt', dur: '17 m' },
          { id: 's7', label: 'Counts reconciled',          owner: 'jerome',  tool: 'hubspot', dur: '2 m' },
          { id: 's8', label: 'Conclusion written up',      owner: 'jerome',  tool: 'chatgpt', dur: '11 m' },
        ],
        variants: [
          { type: 'rework', from: 's7', to: 's6', share: 0.14, label: 'Spot-check on flagged lead' },
          { type: 'detour', after: 's4', rejoin: 's5', share: 0.10, label: 'Personal-account request declined',
            steps: [{ id: 'x1', label: 'Org-account alternative agreed', owner: 'rifadha', tool: 'teams' }] },
          { type: 'skip',   from: 's3', to: 's6', share: 0.06, label: 'Access already held' },
        ],
      },
      {
        id: 'wf7',
        name: 'LinkedIn Master Workbook',
        code: 'WF7',
        cases: 48,
        desc: 'Weekly rebuild: recruiter exports staged, scheduled agent run, USD conversion, duplicate flags, confirmation gate, upload.',
        people: ['jerome', 'zolara'],
        tools: ['sharepoint', 'chatgpt', 'linkedin'],
        steps: [
          { id: 's1', label: 'Recruiter exports staged',  owner: 'zolara', tool: 'sharepoint', dur: null },
          { id: 's2', label: 'Uploads folder verified',   owner: 'jerome', tool: 'sharepoint', dur: '10 m' },
          { id: 's3', label: 'Validation policy applied', owner: 'jerome', tool: 'chatgpt',    dur: '5 m' },
          { id: 's4', label: 'Agent run executed',        owner: 'jerome', tool: 'chatgpt',    dur: '26 m' },
          { id: 's5', label: 'Master workbook rebuilt',   owner: 'jerome', tool: 'sharepoint', dur: '8 m' },
          { id: 's6', label: 'Confirmation gate passed',  owner: 'jerome', tool: 'chatgpt',    dur: '2 m' },
          { id: 's7', label: 'Uploaded to library',       owner: 'jerome', tool: 'sharepoint', dur: '6 m' },
        ],
        variants: [
          { type: 'rework', from: 's4', to: 's2', share: 0.16, label: 'Missing export — recruiter chased' },
          { type: 'detour', after: 's4', rejoin: 's5', share: 0.11, label: 'FX data gap flagged',
            steps: [{ id: 'x1', label: 'Manual FX rate supplied', owner: 'jerome', tool: 'chatgpt' }] },
          { type: 'rework', from: 's6', to: 's4', share: 0.08, label: 'Duplicates re-keyed on Job ID' },
        ],
      },
    ],
  },
  {
    id: 'welfare',
    name: 'People & Welfare',
    lead: 'Samindi De Silva',
    blurb: 'Staff welfare, relief coordination and cross-team care decisions.',
    workflows: [
      {
        id: 'wf2',
        name: 'Relief & Gift Coordination',
        code: 'WF2',
        cases: 34,
        desc: 'Typhoon-relief support: options researched, hamper vs cash debated, budget escalated, policy check, sourcing handed off.',
        people: ['jerome', 'himaya', 'samindi', 'romesh'],
        tools: ['teams', 'portal'],
        steps: [
          { id: 's1', label: 'Affected staff identified',  owner: 'jerome',  tool: 'chatgpt', dur: null },
          { id: 's2', label: 'Gift options researched',    owner: 'jerome',  tool: 'teams',   dur: '5 m' },
          { id: 's3', label: 'Option shared 1:1',          owner: 'jerome',  tool: 'teams',   dur: '1 m' },
          { id: 's4', label: 'Cost estimated (AUD)',       owner: 'himaya',  tool: 'teams',   dur: '2 m' },
          { id: 's5', label: 'Escalated to HR gang',       owner: 'himaya',  tool: 'teams',   dur: '7 m' },
          { id: 's6', label: 'Policy ruling (no cash)',    owner: 'samindi', tool: 'teams',   dur: '7 m' },
          { id: 's7', label: 'Sourcing handed back',       owner: 'jerome',  tool: 'teams',   dur: '5 m' },
        ],
        variants: [
          { type: 'rework', from: 's4', to: 's2', share: 0.18, label: 'Hamper vs cash re-debated' },
          { type: 'detour', after: 's5', rejoin: 's6', share: 0.09, label: 'Record verified in portal',
            steps: [{ id: 'x1', label: 'Team-member record checked', owner: 'himaya', tool: 'portal' }] },
          { type: 'skip',   from: 's3', to: 's5', share: 0.06, label: 'Cost known — straight to HR gang' },
        ],
      },
    ],
  },
];

export const ATLAS = { departments: DEPARTMENTS, people: PEOPLE, tools: TOOLS };
